/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.completeprofileproject.testprofiledb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportOptions;
import com.wavemaker.runtime.data.model.QueryProcedureInput;

import com.completeprofileproject.testprofiledb.models.query.*;

@Service
public class TestProfileDBQueryExecutorServiceImpl implements TestProfileDBQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(TestProfileDBQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("testProfileDBWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(value = "testProfileDBTransactionManager", readOnly = true)
    @Override
    public Page<TestQueryResponse> executeTestQuery(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("testQuery", params, TestQueryResponse.class, pageable);
    }

    @Transactional(value = "testProfileDBTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportTestQuery(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput<TestQueryResponse> queryInput = new QueryProcedureInput<>("testQuery", params, TestQueryResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

}