/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.completeprofileproject.testprofiledb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AllTypes generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`All Types`")
public class AllTypes implements Serializable {

    private Integer id;
    private Integer intColumn;
    private Short shortColumn;
    private Long longColumn;
    private Float floatColumn;
    private Double doubleColumn;
    private Character charColumn;
    private Byte byteColumn;
    private Boolean booleanColumn;
    private Date dateColumn;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`IntColumn`", nullable = true, scale = 0, precision = 10)
    public Integer getIntColumn() {
        return this.intColumn;
    }

    public void setIntColumn(Integer intColumn) {
        this.intColumn = intColumn;
    }

    @Column(name = "`shortColumn`", nullable = true, scale = 0, precision = 10)
    public Short getShortColumn() {
        return this.shortColumn;
    }

    public void setShortColumn(Short shortColumn) {
        this.shortColumn = shortColumn;
    }

    @Column(name = "`longColumn`", nullable = true, scale = 0, precision = 10)
    public Long getLongColumn() {
        return this.longColumn;
    }

    public void setLongColumn(Long longColumn) {
        this.longColumn = longColumn;
    }

    @Column(name = "`floatColumn`", nullable = true, scale = 0, precision = 10)
    public Float getFloatColumn() {
        return this.floatColumn;
    }

    public void setFloatColumn(Float floatColumn) {
        this.floatColumn = floatColumn;
    }

    @Column(name = "`doubleColumn`", nullable = true, scale = 0, precision = 10)
    public Double getDoubleColumn() {
        return this.doubleColumn;
    }

    public void setDoubleColumn(Double doubleColumn) {
        this.doubleColumn = doubleColumn;
    }

    @Column(name = "`charColumn`", nullable = true, length = 1)
    public Character getCharColumn() {
        return this.charColumn;
    }

    public void setCharColumn(Character charColumn) {
        this.charColumn = charColumn;
    }

    @Column(name = "`byteColumn`", nullable = true, scale = 0, precision = 10)
    public Byte getByteColumn() {
        return this.byteColumn;
    }

    public void setByteColumn(Byte byteColumn) {
        this.byteColumn = byteColumn;
    }

    @Column(name = "`booleanColumn`", nullable = true)
    public Boolean getBooleanColumn() {
        return this.booleanColumn;
    }

    public void setBooleanColumn(Boolean booleanColumn) {
        this.booleanColumn = booleanColumn;
    }

    @Column(name = "`dateColumn`", nullable = true)
    public Date getDateColumn() {
        return this.dateColumn;
    }

    public void setDateColumn(Date dateColumn) {
        this.dateColumn = dateColumn;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AllTypes)) return false;
        final AllTypes allTypes = (AllTypes) o;
        return Objects.equals(getId(), allTypes.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}