/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.completeprofileproject.sales.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.completeprofileproject.sales.Table8;

/**
 * Service object for domain model class {@link Table8}.
 */
public interface Table8Service {

    /**
     * Creates a new Table8. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Table8 if any.
     *
     * @param table8 Details of the Table8 to be created; value cannot be null.
     * @return The newly created Table8.
     */
    Table8 create(@Valid Table8 table8);


	/**
     * Returns Table8 by given id if exists.
     *
     * @param table8Id The id of the Table8 to get; value cannot be null.
     * @return Table8 associated with the given table8Id.
	 * @throws EntityNotFoundException If no Table8 is found.
     */
    Table8 getById(Integer table8Id);

    /**
     * Find and return the Table8 by given id if exists, returns null otherwise.
     *
     * @param table8Id The id of the Table8 to get; value cannot be null.
     * @return Table8 associated with the given table8Id.
     */
    Table8 findById(Integer table8Id);

	/**
     * Find and return the list of Table8s by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param table8Ids The id's of the Table8 to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return Table8s associated with the given table8Ids.
     */
    List<Table8> findByMultipleIds(List<Integer> table8Ids, boolean orderedReturn);


    /**
     * Updates the details of an existing Table8. It replaces all fields of the existing Table8 with the given table8.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Table8 if any.
     *
     * @param table8 The details of the Table8 to be updated; value cannot be null.
     * @return The updated Table8.
     * @throws EntityNotFoundException if no Table8 is found with given input.
     */
    Table8 update(@Valid Table8 table8);

    /**
     * Deletes an existing Table8 with the given id.
     *
     * @param table8Id The id of the Table8 to be deleted; value cannot be null.
     * @return The deleted Table8.
     * @throws EntityNotFoundException if no Table8 found with the given id.
     */
    Table8 delete(Integer table8Id);

    /**
     * Deletes an existing Table8 with the given object.
     *
     * @param table8 The instance of the Table8 to be deleted; value cannot be null.
     */
    void delete(Table8 table8);

    /**
     * Find all Table8s matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Table8s.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<Table8> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all Table8s matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Table8s.
     *
     * @see Pageable
     * @see Page
     */
    Page<Table8> findAll(String query, Pageable pageable);

    /**
     * Exports all Table8s matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all Table8s matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the Table8s in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the Table8.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}